<Portal>
                <Dialog visible={visible} onDismiss={hideDialog}>
                    <Dialog.ScrollArea>
                        <ScrollView contentContainerStyle={{ paddingHorizontal: 1 }}>
                            <View style={{ backgroundColor: '' }}>
                                <Text style={{ textAlign: 'center', fontSize: 25, fontFamily: 'headings' }}>Add Pakage Details</Text>
                            </View>
                        </ScrollView>
                    </Dialog.ScrollArea>
                </Dialog>
            </Portal>